### ISSUE TITLE
what the hell is 142.93.90.113 in the peer.referrals???!

### ISSUE THREAD

**Issue by whatsdis** [hyperswarm/network#21]
it's a digitalocean VPS that is connecting to my IP address when I echo out the Peer object from network().on('peers')!!! I've NEVER EVER used digitalocean with hyperswarm. I've used Google Compute Engine before to test hyperswarm but its not running.....

peer: { port: 67838,
  host: 'my.ip.address',
  local: false,
  referrer:
   { id:
      <Buffer .....>,
     port: 33352
,    host: '142.93.90.113'}

**Comment by mafintosh** [comment]
It's one of the bootstrap servers

**Comment by whatsdis** [comment]
oh thank god....I had a small panic attack just now lol

**Comment by whatsdis** [comment]
is it possible to run my own bootstrap servers?

**Comment by mafintosh** [comment]
Yes, def. Just run https://github.com/hyperswarm/dht and pass your ip:port in the bootstrap option to the dht.

**Comment by whatsdis** [comment]
what exactly is the purpose of these bootstrap servers? is it for "punching holes"?

**Comment by bcomnes** [comment]
> what exactly is the purpose of these bootstrap servers? is it for "punching holes"?

Yeah and finding other peers initially.

**Comment by pfrazee** [comment]
I think all peers can punch holes for each other, right? It's not just the bootstrap peers.

**Comment by bcomnes** [comment]
That’s my understanding

**Comment by mafintosh** [comment]
Yep just a series of preshared peers to help you connect. Any set of peers will do
