### ISSUE TITLE
get notified when a peer leaves topic?

### ISSUE THREAD

**Issue by whatsdis** [hyperswarm/network#22]
is there something like `network().on('leave', (peer) => {//triggered whenever a peer leaves or disconnected});`

**Comment by RangerMauve** [comment]
Listen for the `close` event on connections that get emitted inside the `connection` event.

E.g.

```js
net.on('connection', (socket, details) => {
  console.log('new connection!', details)

  socket.once('close', () => {
    console.log('Lost peer')
  })
})
```
